data:
  all: true
rag:
  files:
    exclude: []
    include: []
  folders:
    exclude: []
    include:
    - /home/src/academy/callbacks
    - /home/src/academy/custom
    - /home/src/academy/data_exporters
    - /home/src/academy/data_loaders
    - /home/src/academy/dbt
    - /home/src/academy/extensions
    - /home/src/academy/sensors
    - /home/src/academy/transformers
    - /home/src/academy/utils
