# io_config.yaml
#
# This file stores credentials and connection information for data sources.
#
# For more information: https://docs.mage.ai/development/io_config_setup
version: 0.1.1
default:
  # Default profile created for data IO access.
  # Add your credentials for the source you use, and delete the rest.
  # AWS
  AWS_ACCESS_KEY_ID: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
  AWS_SECRET_ACCESS_KEY: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
  AWS_REGION: "{{ env_var('AWS_REGION') }}"
  AWS_SESSION_TOKEN: "{{ env_var('AWS_SESSION_TOKEN') }}" # Used to generate Redshift credentials
  AWS_ENDPOINT: "{{ env_var('AWS_ENDPOINT') }}"

  # Algolia
  ALGOLIA_APP_ID: "{{ env_var('ALGOLIA_APP_ID') }}"
  ALGOLIA_API_KEY: "{{ env_var('ALGOLIA_API_KEY') }}"
  ALGOLIA_INDEX_NAME: index_name

  # Azure
  AZURE_CLIENT_ID: "{{ mage_secret_var('azure_client_id') }}"
  AZURE_CLIENT_SECRET: "{{ mage_secret_var('azure_client_secret') }}"
  AZURE_DATABRICKS_ACCESS_TOKEN: "{{ env_var('AZURE_DATABRICKS_ACCESS_TOKEN') }}"
  AZURE_DATABRICKS_WORKSPACE_NAME: "{{ env_var('AZURE_DATABRICKS_WORKSPACE_NAME') }}"
  AZURE_STORAGE_ACCOUNT_NAME: "{{ env_var('AZURE_STORAGE_ACCOUNT_NAME') }}"
  AZURE_SUBSCRIPTION_ID: "{{ env_var('AZURE_SUBSCRIPTION_ID') }}"
  AZURE_TENANT_ID: "{{ env_var('azure_tenant_id') }}"
  AZURE_FUNCTION_APP: "{{ env_var('AZURE_FUNCTION_APP') }}"
  AZURE_FUNCTION_URL_CODE: "{{ env_var('AZURE_FUNCTION_URL_CODE') }}"
  AZURE_RESOURCE_GROUP: "{{ env_var('AZURE_RESOURCE_GROUP') }}"
  POWER_BI_WORKSPACE_ID: "{{ env_var('POWER_BI_WORKSPACE_ID') }}"


  MICROSOFT_FABRIC_WAREHOUSE_NAME: "{{ mage_secret_var('fabric_warehouse_name') }}"
  MICROSOFT_FABRIC_WAREHOUSE_ENDPOINT: "{{ mage_secret_var('fabric_warehouse_endpoint') }}"

  # Chroma
  CHROMA_COLLECTION: collection_name
  CHROMA_PATH: path

  # Clickhouse
  CLICKHOUSE_DATABASE: default
  CLICKHOUSE_HOST: host.docker.internal
  CLICKHOUSE_INTERFACE: http
  CLICKHOUSE_PASSWORD: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
  CLICKHOUSE_PORT: 8123
  CLICKHOUSE_USERNAME: "{{ env_var('CLICKHOUSE_USERNAME') }}"
  # CLICKHOUSE_SSL_CA_CERT: "{{ env_var('CLICKHOUSE_SSL_CA_CERT') }}"  # Optional

  # Databricks SQL
  DATABRICKS_ACCESS_TOKEN: "{{ env_var('DATABRICKS_ACCESS_TOKEN') }}"
  DATABRICKS_DATABASE: database  # Databricks Catalog
  DATABRICKS_HOST: dbc-123456-abcd.cloud.databricks.com
  DATABRICKS_HTTP_PATH: "/sql/1.0/warehouses/abcd1234"
  DATABRICKS_SCHEMA: schema

  # Druid
  DRUID_HOST: hostname
  DRUID_PASSWORD: "{{ env_var('DRUID_PASSWORD') }}"
  DRUID_PATH: /druid/v2/sql/
  DRUID_PORT: 8082
  DRUID_SCHEME: http
  DRUID_USER: "{{ env_var('DRUID_USER') }}"

  # DuckDB
  DUCKDB_DATABASE: example.duckdb
  DUCKDB_SCHEMA: main

  # Google
  GOOGLE_SERVICE_ACC_KEY:
    type: service_account
    project_id: lyrical-drive-439810-j7
    private_key_id: 2caf7a23baca12b110ed603fd69a54b7f549f1a4
    private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDbdRtoPymH4Gqx\nDuQGbfnPkm7zbrK9gxwuqMCP08d+WGGV2HTh8hgnfzzSy9RZYz+6zzZk/YbmTfho\naqbYerUpz1ibcZY5TKQG7r8rvz8DlVcl2YB7JOzuUm/UEnOVtMfng3SRDmHwBYCe\nGdN/TrWV447c/8GCdZddv6ayeRZ6QJJUYTI2nWY71hNMx16VmQg9sOB2TzkJoFN5\nblGaEaTmQZemmn7AqWZWLFF7OeZYJ8FU7HuoQxu+bZyPDdjU0QzCYnwE++D3o7x1\nf+MyiOl6n22Z34kcWERf0hWSpmv+mAORJ7B9tMhrJ9qpSP312TKYy/+iyuvXbjzh\nVREKgw0JAgMBAAECggEAARW/IPDO/8D4Rg/QyMdaaNBMhB+T+qPfS8vBx/RAFDvT\nn64GReewfuF+J3yifB6lfgLwPeeS9yiDheChGojgxGgmA/63w2jBltcvUsQLR7VB\nTQqaPAGeuj7mFqJQt/jA1EAuH1l22nzsedue1A5Lj4Ykeqs5BbAXI3uDE3bNyaTt\nvBDctY+e7tnjxRaaFLe52xYvKQjzpvOzQ8a92VTKTOe0sHhVJ/uHN7nmeOg47uO/\nOQ3hZwFviLnZX+zp3iL+wlswtPcmtT1llspJdyNQxiI2TIRXKdQ/ngiI7Yo9pdro\nN4SVXmKGLcW6axD3PzSkc6LbRlwHKhJ5bUZZctJKEQKBgQDzuU80yrL1gsw39dLN\nUHMyYiQbWyRGTwONO8SOY+ATQv6jfJnjeawanQmi+dMKdepmfEoh+LUa4aZwGJGD\njOVbaY/OTx0nwroBgLzrbjQeY8cyIKw/azjlsICsQSYCdR3gTeNJwXgHhWZDcJcT\nhQxeLfQLEa3IJuDf3qE7SohNCwKBgQDmguUhbtDEGl0ehH0gB6u0B8PiKuG2wXHv\nvah6dnqNI0Gxp51YqGyLha8qtQBE4bPI1JoWnYKD5SqmUemImWlnln4V4jqixjaB\n62DKZOY+4eragJitHQtDmRMFtCI9Nt2i7U0uqVvpv+ddtHDg0tznKQUQDOyHKoRH\nFdeb75gSuwKBgQCwntjkdAQuYOQnpZBnU2a322E5JdpqzTXQssBlQ8GNk94+kbxf\nmbv76VOjdJHYoc0FCgsbBUYRPfdEgrlo8MEBdsVNCA4j0zzCfA3sOwewAjTHgd/x\ncX1hDoCg0/F8lGzbMPaGa5rVMHoEY2JINgHZeknBf8VFJ8+MzKRg+ElAMwKBgBhf\n6v64CxdReltJwzlp1jw5PfticW+z0Op68Z/Re3AFNGMmyDqhxKiUQEuRzC98dlhc\nMtcFXNG5n+LqcnlhT4YGodqKi4y+zPC8BQYh2T75AK6OPpa/pXtGan6F58D1VkZu\nNWUjv3ZeNobwF6eOZJGFAuYJl9FLK6Wgp6Xzle8VAoGBAJazVR7yiX21KyCuywG/\n11ALSMykz4xIekqe8GxGarZm8q2dfpIn5zF2pqNA/WyWIQywtFzXcmd6jlwNUtbF\na28ll0onV90upBJbg7YXb0hxNtbGHlFkKAldvJRMqJb/PwlPOQCaPk6dqOaYAMSB\nZfoh+8vlsNRjNzdxaiPssl7K\n-----END PRIVATE KEY-----\n"
    client_email: lyrical-drive-439810-j7@appspot.gserviceaccount.com
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://accounts.google.com/o/oauth2/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/your_service_account_email"
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/home/src/academy/google_credential_storage.json"
  GOOGLE_LOCATION: US # Optional

  # MongoDB
  # Specify either the connection string or the (host, password, user, port) to connect to MongoDB.
  MONGODB_CONNECTION_STRING: "mongodb://{username}:{password}@{host}:{port}/"
  MONGODB_HOST: host
  MONGODB_PORT: 27017
  MONGODB_USER: "{{ env_var('MONGODB_USER') }}"
  MONGODB_PASSWORD: "{{ env_var('MONGODB_PASSWORD') }}"
  MONGODB_DATABASE: database
  MONGODB_COLLECTION: collection

  # MSSQL
  MSSQL_DATABASE: database
  MSSQL_SCHEMA: schema
  MSSQL_DRIVER: "ODBC Driver 18 for SQL Server"
  MSSQL_HOST: host
  MSSQL_PASSWORD: "{{ env_var('MSSQL_PASSWORD') }}"
  MSSQL_PORT: 1433
  MSSQL_USER: "{{ env_var('MSSQL_USER') }}"

  # MySQL
  MYSQL_DATABASE: database
  MYSQL_HOST: host
  MYSQL_PASSWORD: "{{ env_var('MYSQL_PASSWORD') }}"
  MYSQL_PORT: 3306
  MYSQL_USER: "{{ env_var('MYSQL_USER') }}"

  # Pinot
  PINOT_HOST: hostname
  PINOT_PASSWORD: "{{ env_var('PINOT_PASSWORD') }}"
  PINOT_PATH: /query/sql
  PINOT_PORT: 8000
  PINOT_SCHEME: http
  PINOT_USER: "{{ env_var('PINOT_USER') }}"

  # PostgreSQL
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: postgres
  POSTGRES_SCHEMA: public # Optional
  POSTGRES_USER: "{{ env_var('POSTGRES_USER') }}"
  POSTGRES_PASSWORD: "{{ env_var('POSTGRES_PASSWORD') }}"
  POSTGRES_HOST: hostname
  POSTGRES_PORT: 5432
  # POSTGRES_SSL_MODE: "{{ env_var('POSTGRES_SSL_MODE') }}"  # Optional
  # POSTGRES_SSL_ROOTCERT: "{{ env_var('POSTGRES_SSL_ROOTCERT') }}"  # Optional
  # POSTGRES_SSL_CERT: "{{ env_var('POSTGRES_SSL_CERT') }}"  # Optional
  # POSTGRES_SSL_KEY: "{{ env_var('POSTGRES_SSL_KEY') }}"  # Optional

  # Qdrant
  QDRANT_COLLECTION: collection
  QDRANT_PATH: path

  # Redshift
  REDSHIFT_SCHEMA: public # Optional
  REDSHIFT_DBNAME: redshift_db_name
  REDSHIFT_HOST: redshift_cluster_id.identifier.region.redshift.amazonaws.com
  REDSHIFT_PORT: 5439
  REDSHIFT_TEMP_CRED_USER: "{{ env_var('REDSHIFT_TEMP_CRED_USER') }}"
  REDSHIFT_TEMP_CRED_PASSWORD: "{{ env_var('REDSHIFT_TEMP_CRED_PASSWORD') }}"
  REDSHIFT_DBUSER: "{{ env_var('REDSHIFT_DBUSER') }}"
  REDSHIFT_CLUSTER_ID: redshift_cluster_id
  REDSHIFT_IAM_PROFILE: default

  # Snowflake
  SNOWFLAKE_USER: "{{ env_var('SNOWFLAKE_USER') }}"
  SNOWFLAKE_PASSWORD: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
  SNOWFLAKE_ACCOUNT: account_id.region
  # SNOWFLAKE_DEFAULT_WH: "{{ env_var('SNOWFLAKE_DEFAULT_WH') }}"  # Optional default warehouse
  # SNOWFLAKE_DEFAULT_DB: "{{ env_var('SNOWFLAKE_DEFAULT_DB') }}"  # Optional default database
  # SNOWFLAKE_DEFAULT_SCHEMA: "{{ env_var('SNOWFLAKE_DEFAULT_SCHEMA') }}"  # Optional default schema
  # SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE') }}"  # Optional private key passphrase
  # SNOWFLAKE_PRIVATE_KEY_PATH: "/path/to/private/key"  # Optional private key path
  # SNOWFLAKE_ROLE: "{{ env_var('SNOWFLAKE_ROLE') }}"  # Optional role name
  # SNOWFLAKE_TIMEOUT: 300  # Optional timeout in seconds

  # SQLite
  sqlite:
    database: example.db

  # Trino
  trino:
    catalog: postgresql                       # Change this to the catalog of your choice
    host: 127.0.0.1
    http_headers:
      X-Something: 'mage=power'
    http_scheme: http
    password: "{{ env_var('TRINO_PASSWORD') }}"  # Optional
    port: 8080
    schema: core_data
    session_properties:                       # Optional
      acc01.optimize_locality_enabled: false
      optimize_hash_generation: true
    source: trino-cli                         # Optional
    user: "{{ env_var('TRINO_USER') }}"
    verify: /path/to/your/ca.crt              # Optional

  # Weaviate
  WEAVIATE_ENDPOINT: https://some-endpoint.weaviate.network
  WEAVIATE_INSTANCE_API_KEY: "{{ env_var('WEAVIATE_INSTANCE_API_KEY') }}"
  WEAVIATE_INFERENCE_API_KEY: "{{ env_var('WEAVIATE_INFERENCE_API_KEY') }}"
  WEAVIATE_COLLECTION: collectionn_name
